config/routes.rb
Rails.application.routes.draw do
  devise_for :traders
  devise_for :users

  mount ActionCable.server => '/cable'

  root to: "pages#home"

  resources :traders, only: %i[show]
  resources :users, only: %i[show]
  resources :chats, only: %i[index create] do
    resources :messages, only: %i[index create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
# == Schema Information
#
# Table name: chats
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  trader_id  :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_chats_on_trader_id  (trader_id)
#  index_chats_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (trader_id => traders.id)
#  fk_rails_...  (user_id => users.id)
#
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :trader

  has_many :messages, dependent: :destroy

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id              :bigint           not null, primary key
#  content         :text
#  messagable_type :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  chat_id         :bigint           not null
#  messagable_id   :bigint           not null
#
# Indexes
#
#  index_messages_on_chat_id     (chat_id)
#  index_messages_on_messagable  (messagable_type,messagable_id)
#
# Foreign Keys
#
#  fk_rails_...  (chat_id => chats.id)
#
class Message < ApplicationRecord

  belongs_to :chat
  belongs_to :messagable, polymorphic: true

end

app/models/trader.rb
# == Schema Information
#
# Table name: traders
#
#  id                     :bigint           not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  phone                  :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_traders_on_email                 (email) UNIQUE
#  index_traders_on_reset_password_token  (reset_password_token) UNIQUE
#
class Trader < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chats, dependent: :destroy
  has_many :messages, as: :messagable

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  phone                  :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chats, dependent: :destroy
  has_many :messages, as: :messagable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_customer
    @current_customer = current_trader || current_user
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def create
    @chat = current_user.chats.create(chat_params)

    redirect_to chat_messages_path(@chat)
  end

  private

  def chat_params
    params.permit(:trader_id)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_chat
  before_action :current_customer

  def index
    @messages = @chat.messages
  end

  def create
    participant = current_user || current_trader
    message = participant.messages.create(message_params.merge(chat: @chat))

    ActionCable.server.broadcast('chats/1', { message: message })
  end

  private

  def set_chat
    @chat = Chat.find(params[:chat_id])
  end

  def message_params
    params.permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home; end

end

app/controllers/traders_controller.rb
class TradersController < ApplicationController

  def show
    @trader = Trader.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<div id="chat_messages" data-chat-id="<%= @chat.id %>" data-customer-id="<%= @current_customer.id %>">
  <% @messages.each do |message| %>
    <p><%= message.content %></p>
  <% end %>
</div>
<div id="new_message"></div>
<div>
  <%= form_with(model: @message, url: chat_messages_path(@chat), method: :post) do |form| %>
    <%= form.text_field :content %>
    
    <%= form.submit "Send" %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="flex flex-col items-center h-screen justify-center">
  <div class="text-2xl font-bold mb-10">MarketPlace App</div>
  <div>
    <p class="mb-4">
      Sign in as
      <%= link_to 'User', new_user_session_path, class: "hover:text-sky-500" %>
    </p>
    <p>
      Are you a trader? Sign in as
      <%= link_to 'Trader', new_trader_session_path, class: "hover:text-sky-500" %>
    </p>
  </div>
</div>

app/views/traders/show.html.erb
<ul>
  <li>First name: <%= @trader.first_name %></li>
  <li>Last name: <%= @trader.last_name %></li>
  <li>Phone: <%= @trader.phone %></li>
  <li>E-mail: <%= @trader.email %></li>
</ul>

<div>
  <%= form_with(url: chats_path, method: :post) do |form| %>
    <%= form.hidden_field :trader_id, value: @trader.id %>
    
    <%= form.submit "Start chat" %>
  <% end %>
</div>

app/views/users/show.html.erb
<ul>
  <li>First name: <%= @user.first_name %></li>
  <li>Last name: <%= @user.last_name %></li>
  <li>Phone: <%= @user.phone %></li>
  <li>E-mail: <%= @user.email %></li>
</ul>